
// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import * as dotenv from "dotenv";
dotenv.config({ path: "src/modules/auth/.env" });
import { defineConfig, env } from "prisma/config";

// ============================================
// AUTH DOMAIN PRISMA CONFIG
// ============================================
// When switching to another domain, update these paths:
// - Catalog: src/modules/catalog/prisma/...
// - Inventory: src/modules/inventory/prisma/...
// - Orders: src/modules/orders/prisma/...

export default defineConfig({
  schema: "src/modules/auth/prisma/schema.prisma",
  migrations: {
    path: "src/modules/auth/prisma/migrations",
  },
  engine: "classic",
  datasource: {
    url: env("DATABASE_URL"),
  },
});
